#!/bin/sh

# Displays different icons depending on the current volume level.

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
    icon=""
elif [ "$vol" -lt "30" ]; then
    icon=""
else
    icon=""
fi

printf "%s %s%%\\n" "$icon" "$vol"
